import type { Metadata } from "next";
import { Outfit } from "next/font/google";
// @ts-ignore
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "AI Content Generator",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png',
    apple: '/logo.png',
  },
};
const outfit = Outfit({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
